name: Generate Test Coverage

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
        GO111MODULE: on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: ['1.20', '1.21']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Gather dependencies
      run: go mod download
    - name: Test
      run: |
        go test -v -coverpkg ./... -cover ./... -coverprofile coverage.out
        go tool cover -func coverage.out -o coverage.out 
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: arshamalh/dockeroller

