name: Generate Test Coverage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
        GO111MODULE: on
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go: ['1.20', '1.21']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - name: Gather dependencies
      run: go mod download
    - name: Test
      run: |
        go test -v -coverpkg ./... -cover ./... -coverprofile coverage.out
        go tool cover -func coverage.out -o coverage.out 
    - name: Go Coverage Badge
      uses: tj-actions/coverage-badge-go@v2
      if: ${{ runner.os == 'Linux' && matrix.go == '1.21' }}
      with:
        green: 80
        filename: coverage.out
    - uses: stefanzweifel/git-auto-commit-action@v5
      id: auto-commit-action
      with:
        commit_message: Apply Code Coverage Badge
        skip_fetch: true
        skip_checkout: true
        file_pattern: ./README.md
        branch: coverage-badge
        create_branch: true
    - name: Push Changes
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: coverage-badge
    - name: Create Pull Request
      run: gh pr create -B main -H coverage-badge --title 'Merge coverage-badge into main' --body 'Created by Github action'
      env:
        github_token: ${{ github.token }}

# TODO: package below might be used instead of last three steps:
#  - https://github.com/marketplace/actions/create-pull-request
