name: Go Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - .github/workflows/main.yaml
      - .github/workflows/gen_coverage.yaml
      - assets
      - Makefile
  pull_request:
    types: 
      - opened
      - reopened
      - review_requested
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - .github/workflows/main.yaml
      - .github/workflows/gen_coverage.yaml
      - assets
      - Makefile
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.0

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Check code style
      run: gofmt -l -s $(find . -type f -name '*.go' -not -path "./vendor/*")
